### ISSUE TITLE
Add Firefox Support

### ISSUE THREAD

**Issue by kusold** [nthitz/pluggedN#44]
https://blog.mozilla.org/addons/2014/06/05/how-to-develop-firefox-extension/

I'm hoping to implement PluggedN as an extension this week. I don't see any reason why it wouldn't work. Probably just requires extending the gulp build process.

**Comment by nthitz** [comment]
Yeah it shouldn't really be too tricky. Basically just need a way to inject `dat.gui.js` `theme.js` and `bookmarklet.js` and it should be running. Haven't taken the time to do for FF just cause I don't use it much for plug. You are definitely welcome to try to get it up and running!

**Comment by nthitz** [comment]
FF users can use a Greasemonkey script as provided by @kusold :)
